SAVE_BUTTON_CSS = ".btn-primary"
ERROR_MESSAGE1 = ".col-12:nth-child(1) > .text-danger"
ERROR_MESSAGE2 = ".col-12:nth-child(2) > .text-danger"
ERROR_MESSAGE3 = ".col-12:nth-child(3) > .text-danger"
ERROR_MESSAGE4 =  ".col-12:nth-child(4) > .text-danger"
ERROR_MESSAGE5 = ".col-12:nth-child(5) > .text-danger:nth-child(3)"
ERROR_MESSAGE6 = ".text-danger:nth-child(5)"
EDUCATION = "EducationStatus"
EDUCATION_STATUS = "EducationStatus"
UNIVERSITY = "University"
DEPARTMENT = "Department"
START_YEAR = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[4]/div[1]/div/input"
START_YEAR_CALENDER =  ".react-datepicker__year-text:nth-child(4)"
FINISH_YEAR =  "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[5]/div[1]/div/input"
FINISH_YEAR_CALENDER = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[5]/div[2]/div[2]/div/div/div[2]/div[2]/div/div[8]"
TOAST_MESSAGE =  ".toast-body"
DELETE_EDUCATION = ".my-grade:nth-child(1) .grade-delete"
ALERT_MESSAGE = ".alert-message"
YES_BUTTON = ".btn-yes"