# Profil Bilgileri -> Deneyeimlerim Sayfası Locators
# https://tobeto.com/profilim/profilimi-duzenle/deneyimlerim

from selenium.webdriver.common.by import By
import constants.my_experiences_page_constants as mg

class myExperiencesPageLocators:
    
    # PAGE FORM
    CORPORATION_NAME = (By.XPATH, mg.CORPORATION_NAME_XPATH)
    POSITION = (By.XPATH, mg.POSITION_XPATH)
    SECTOR = (By.XPATH, mg.SECTOR_XPATH)
    SELECT_COUNTRY_DROPDOWN = (By.XPATH, mg.SELECT_COUNTRY_DROPDOWN_XPATH)
    START_CALENDAR = (By.XPATH, mg.START_CALENDAR_XPATH)
    START_DATE = (By.CSS_SELECTOR, mg.START_DATE_CSS)
    FINISH_CALENDAR = (By.XPATH, mg.FINISH_CALENDAR_XPATH)
    FINISH_DATE =(By.CSS_SELECTOR, mg.FINISH_DATE_CSS)
    SAVE_BUTTON = (By.CSS_SELECTOR, mg.SAVE_BUTTON_XPATH)

    TOAST_MESSAGE = (By.CSS_SELECTOR, mg.TOAST_MESSAGE_CSS)

    # JOB DESC, DELETE EXPERINCE
    THREE_DOTS_BUTTON = (By.XPATH, mg.THREE_DOTS_BUTTON_XPATH)
    JOB_DESC = (By.XPATH, mg.JOB_DESC_XPATH)
    CLOSE_BUTTON = (By.XPATH, mg.CLOSE_BUTTON_XPATH)
    DELETE_BUTTON = (By.CSS_SELECTOR, mg.DELETE_BUTTON_CSS)
    DELETE_CONFIRM_MESSAGE = (By.XPATH, mg.DELETE_CONFIRM_MESSAGE_XPATH)
    NO_BUTTON = (By.XPATH, mg.NO_BUTTON_XPATH)
    YES_BUTTON = (By.XPATH, mg.YES_BUTTON_XPATH)

    # necessary warning fields
    CORPORATION_NAME_WARNING_FIELD = (By.CSS_SELECTOR, mg.CORPORATION_NAME_WARNING_FIELD_CSS)
    POSITION_WARNING_FIELD = (By.CSS_SELECTOR, mg.POSITION_WARNING_FIELD_CSS)
    SECTOR_WARNING_FIELD = (By.CSS_SELECTOR, mg.SECTOR_WARNING_FIELD_CSS)
    START_DATE_WARNING_FIELD = (By.CSS_SELECTOR, mg.START_DATE_WARNING_FIELD_CSS)
    FINISH_DATE_WARNING_FIELD = (By.CSS_SELECTOR, mg.FINISH_DATE_WARNING_FIELD_CSS)
