# Generated by Selenium IDE
# Profil Bilgileri -> Eğitim Hayatım Düzenleme sayfası Locators
#Universite ve Bolum text hatası testi
# https://tobeto.com/profilim/profilimi-duzenle/egitim-hayatim
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

import tests.loginTests.test_validLogin as login
from pages.myeducationlife_page import myeducationlife_page 

from time import sleep


class TestCountinueBox():
 
  def setup_method(self):
    # as a precondition user should be logged in
    valid_login = login.TestvalidLogin() 
    valid_login.setup_method()
    valid_login.test_validLogin()
    self.driver = valid_login.getDriver()
    
    self.driver.delete_all_cookies
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  
  def test_continueBox(self):
    self.driver.get("https://tobeto.com/profilim/profilimi-duzenle/egitim-hayatim")
    self.driver.set_window_size(1552, 832)

    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "checkbox")))
    self.driver.find_element(By.NAME, "checkbox").click()
    sleep(5)
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".col-12:nth-child(5) .form-control")))
    self.driver.close()
  
