# Generated by Selenium IDE
# Profil Bilgileri -> Eğitim Hayatım Düzenleme sayfası Locators
# https://tobeto.com/profilim/profilimi-duzenle/egitim-hayatim
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

import tests.loginTests.test_validLogin as login
from pages.myeducationlife_page import myeducationlife_page 


class TestMyeducationlifeerror():
 


  def setup_method(self):
    # as a precondition user should be logged in
    valid_login = login.TestvalidLogin() 
    valid_login.setup_method()
    valid_login.test_validLogin()
    self.driver = valid_login.getDriver()
    
    self.driver.delete_all_cookies
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()

  def test_myeducationlifeerror(self):
    self.driver.get("https://tobeto.com/profilim/profilimi-duzenle/egitim-hayatim")
    self.driver.set_window_size(1552, 832)
    
    save_button = myeducationlife_page.get_save_button_element(self)
    save_button.click()

    error_message1 = myeducationlife_page.get_error_message1(self)
    assert error_message1.text == "Doldurulması zorunlu alan*"

    error_message2 = myeducationlife_page.get_error_message2(self)
    assert error_message2.text == "Doldurulması zorunlu alan*"

    error_message3 = myeducationlife_page.get_error_message3(self)
    assert error_message3.text == "Doldurulması zorunlu alan*"

    error_message4 = myeducationlife_page.get_error_message4(self)
    assert error_message4.text == "Doldurulması zorunlu alan*"

    error_message5 = myeducationlife_page.get_error_message5(self)
    assert error_message5.text == "Doldurulması zorunlu alan*"

    error_message6 = myeducationlife_page.get_error_message6(self)
    assert error_message6.text == "Doldurulması zorunlu alan*"
    self.driver.close()
  
