# Generated by Selenium IDE
# Profil Bilgileri -> Eğitim Hayatım Düzenleme sayfası Locators
#Universite ve Bolum text hatası testi
# https://tobeto.com/profilim/profilimi-duzenle/egitim-hayatim
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

import tests.loginTests.test_validLogin as login
from pages.myeducationlife_page import myeducationlife_page 

from time import sleep


class TestUniversity():
 


  def setup_method(self):
    # as a precondition user should be logged in
    valid_login = login.TestvalidLogin() 
    valid_login.setup_method()
    valid_login.test_validLogin()
    self.driver = valid_login.getDriver()
    
    self.driver.delete_all_cookies
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_universitytext(self):
    self.driver.get("https://tobeto.com/profilim/profilimi-duzenle/egitim-hayatim")
    self.driver.set_window_size(1552, 832)
    
    Education = myeducationlife_page.get_education(self)
    Education.click()
    
    education_status = myeducationlife_page.get_education_status(self)
    education_status.find_element(By.XPATH, "//option[. = 'Lisans']").click()

    university = myeducationlife_page.get_university(self)
    university.send_keys("d")
    
    department = myeducationlife_page.get_department(self)
    department.send_keys("d")

    start_year = myeducationlife_page.get_start_year(self)
    start_year.click()

    start_year_calender = myeducationlife_page.get_start_year_calender(self)
    start_year_calender.click()
   
    
    finish_year = myeducationlife_page.get_finish_year(self)
    finish_year.click()

    finish_year_calender = myeducationlife_page.get_finish_year_calender(self)
    finish_year_calender.click()
  
    save_button = myeducationlife_page.get_save_button_element(self)
    save_button.click()

    error_message2 = myeducationlife_page.get_error_message2(self)
    assert error_message2.text == "En az 2 karakter girmelisiniz"

    error_message3 = myeducationlife_page.get_error_message3(self)
    assert error_message3.text == "En az 2 karakter girmelisiniz"

    sleep(5)
  
