# Generated by Selenium IDE
# Profil Bilgileri -> Eğitim Hayatım Düzenleme sayfası Locators
#Egitim bilgilerini silme testi
# https://tobeto.com/profilim/profilimi-duzenle/egitim-hayatim
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

import tests.loginTests.test_validLogin as login
from pages.myeducationlife_page import myeducationlife_page 

from time import sleep


class TestDeleteEducaiton():
 
  def setup_method(self):
    # as a precondition user should be logged in
    valid_login = login.TestvalidLogin() 
    valid_login.setup_method()
    valid_login.test_validLogin()
    self.driver = valid_login.getDriver()
    
    self.driver.delete_all_cookies
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_deleteeducation(self):
    self.driver.get("https://tobeto.com/profilim/profilimi-duzenle/egitim-hayatim")
    self.driver.set_window_size(1552, 832)

    delete_education = myeducationlife_page.get_delete_education_element(self)
    delete_education.click()

    alert_message = myeducationlife_page.get_alert_message(self)
    assert alert_message.text == "Seçilen eğitimi silmek istediğinize emin misiniz?"

    yes_button = myeducationlife_page.get_yes_button(self)
    yes_button.click()

    toast_message = myeducationlife_page.get_toast_messageelement(self)
    assert toast_message.text == "• Eğitim kaldırıldı."

    sleep(5)
  
