#3 adet medya hesabı eklenmesi test edilecektir.
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from time import sleep
from pages.my_media_account_page import MediaAccountPage
import tests.loginTests.test_validLogin as login

class TestAdding3mediaaccounts():
  def setup_method(self, method):
    valid_login = login.TestvalidLogin()
    valid_login.setup_method()
    valid_login.test_validLogin()
    self.driver = valid_login.getDriver()
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_adding3mediaaccounts(self):
    self.driver.get("https://tobeto.com/profilim/profilimi-duzenle/medya-hesaplarim")
    #self.driver.set_window_size(1382, 744)
    media_dropdown=MediaAccountPage.get_dropdown_button_element(self)
    media_dropdown.click()
    media_dropdown.find_element(By.XPATH, "//option[. = 'LinkedIn']").click()
    media_input=MediaAccountPage.get_media_url_text_element(self)
    media_input.click()
    media_input.send_keys("https://www.linkedin.com/company/tobeto/")
    save_button=MediaAccountPage.get_save_button_element(self)
    save_button.click()
    sleep(5)
    media3message=MediaAccountPage.get_3media_account_element(self)
    assert media3message.text == "En fazla 3 adet medya seçimi yapılabilir."

    media_dropdown2=MediaAccountPage.get_dropdown_button_element(self)
    media_dropdown2.click()
    media_dropdown2.find_element(By.XPATH, "//option[. = 'Instagram']").click()
    media_input2=MediaAccountPage.get_media_url_text_element(self)
    media_input2.click()
    media_input2.send_keys("https://www.instagram.com/tobeto_official/")
    save_button2=MediaAccountPage.get_save_button_element(self)
    save_button2.click()
    sleep(5)
    # element = self.driver.find_element(By.CSS_SELECTOR, ".btn-primary")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element).perform()
    # element = self.driver.find_element(By.CSS_SELECTOR, "body")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element, 0, 0).perform()
    media_dropdown3=MediaAccountPage.get_dropdown_button_element(self)
    media_dropdown3.click()
    media_dropdown3.find_element(By.XPATH, "//option[. = 'Github']").click()

    media_input3=MediaAccountPage.get_media_url_text_element(self)
    media_input3.click()
    media_input3.send_keys("https://github.com/ssinemarslan")
    save_button=MediaAccountPage.get_save_button_element(self)
    save_button.click()
    sleep(5)
    WebDriverWait(self.driver, 0.5).until(expected_conditions.invisibility_of_element_located((By.CSS_SELECTOR, ".btn-primary")))
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".btn-primary")
    assert len(elements) == 0
  
