# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from time import sleep
from pages.my_media_account_page import MediaAccountPage
import tests.loginTests.test_validLogin as login

class TestAddmediaaccount():
  def setup_method(self, method):
    valid_login = login.TestvalidLogin()
    valid_login.setup_method()
    valid_login.test_validLogin()
    self.driver = valid_login.getDriver()
  
  def teardown_method(self, method):
    self.driver.quit()
    
  def test_addmediaaccount(self):
    self.driver.get("https://tobeto.com/profilim/profilimi-duzenle/medya-hesaplarim")
    #self.driver.set_window_size(1382, 744)
    media_dropdown=MediaAccountPage.get_dropdown_button_element(self)
    media_dropdown.click()
    sleep(5)
    media_dropdown.find_element(By.XPATH, "//option[. = 'Github']").click()

    media_input=MediaAccountPage.get_media_url_text_element(self)
    media_input.click()
    sleep(5)
    media_input.send_keys("https://github.com/ssinemarslan")
    save_button=MediaAccountPage.get_save_button_element(self)
    save_button.click()
    toast_body=MediaAccountPage.get_toastbody_element(self)
    #toast_body=WebDriverWait(self.driver, 10).until(ec.presence_of_element_located(((By.CSS_SELECTOR,".toast-body"))))
    assert toast_body.text == "• Sosyal medya adresiniz başarıyla eklendi."
    sleep(5)
    
    
    
  
