# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

import tests.loginTests.test_validLogin as login
from pages.certificate_page import CertificatePage
from time import sleep


class TestDeletecertificatecancel():
  def setup_method(self, method):
    valid_login = login.TestvalidLogin()
    valid_login.setup_method()
    valid_login.test_validLogin()
    self.driver = valid_login.getDriver()
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_deletecertificatecancel(self):
    self.driver.get("https://tobeto.com/profilim/profilimi-duzenle/sertifikalarim")
    dustbin_button=CertificatePage.get_dustbin_button_element(self)
    dustbin_button.click()
    no_button=CertificatePage.get_no_button_element(self)
    no_button.click()

