# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from time import sleep
from pages.certificate_page import CertificatePage
import tests.loginTests.test_validLogin as login

class TestDowlandcertificate():
  def setup_method(self, method):
    valid_login = login.TestvalidLogin()
    valid_login.setup_method()
    valid_login.test_validLogin()
    self.driver = valid_login.getDriver()
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_dowlandcertificate(self):
    self.driver.get("https://tobeto.com/profilim/profilimi-duzenle/sertifikalarim")
    #self.driver.set_window_size(1382, 744)
    sleep(5)
    dowland_button=CertificatePage.get_dowland_button_element(self)
    dowland_button.click()
    
  
