# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from time import sleep
from pages.my_profile_page import MyProfilePage
import tests.loginTests.test_validLogin as login

class TestEditmyprofile():
  def setup_method(self, method):
    valid_login = login.TestvalidLogin()
    valid_login.setup_method()
    valid_login.test_validLogin()
    self.driver = valid_login.getDriver()
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_editmyprofile(self):
    self.driver.get("https://tobeto.com/profilim")
    #self.driver.set_window_size(1382, 744)
    edit_button=MyProfilePage.get_edit_button_element(self)
    edit_button.click()
    myprofile=MyProfilePage.get_myprofile_element(self)
    assert myprofile.text == "Kişisel Bilgilerim"
  
