# Test Senaryosunun Adı: Profil Bilgileri altında deneyimlerim bölümü bilgi ekleme/güncelleme kontrolleri
# TEST CASE 5: Zorunlu alanlar 5 karakterden az karakter uyarı kontrolü

# Profil Bilgileri -> Deneyimlerim Sayfası 
# https://tobeto.com/profilim/profilimi-duzenle/deneyimlerim

# Generated by Selenium IDE
import pytest
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

import tests.loginTests.test_validLogin as login
import constants.my_experiences_page_constants as gc
from pages.my_experiences_page import MyExperiencesPage
from time import sleep

class TestInvalidInputs():
  def setup_method(self,logged_in_fixture):
    # as a precondition user should be logged in
    valid_login = login.TestvalidLogin() 
    valid_login.setup_method()
    valid_login.test_validLogin()
    self.driver = valid_login.getDriver()
    
    self.driver.delete_all_cookies
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
    
  #@pytest.mark.skip()
  def test_invalidInputs(self):
     self.driver.get("https://tobeto.com/profilim/profilimi-duzenle/deneyimlerim")

     # go to page "Deneyimlerim", böyle gitmesi daha hızlı diye açtım bi
    #  WebDriverWait(self.driver, 30).until(ec.invisibility_of_element_located(((By.CSS_SELECTOR, ".toast-body"))))

    #  user_profile_button = WebDriverWait(self.driver, 30).until(ec.presence_of_element_located((By.XPATH, gc.USER_PROFILE_BUTTON_XPATH)))
      
    #  user_profile_button.click()
    #  user_profile_info_button = WebDriverWait(self.driver, 30).until(ec.visibility_of_element_located((By.XPATH, "//*[@id='__next']/div/nav/div[1]/div/div/div[2]/ul/li[1]/a")))
    #  user_profile_info_button.click()

    #  is_on_profile_page = WebDriverWait(self.driver, 30).until(ec.visibility_of_element_located((By.XPATH, "//*[@id='__next']/div/main/section/div/div/div[1]/div/a[1]/span[2]")))
    #  assert is_on_profile_page.text == "Kişisel Bilgilerim"
    #  user_experiences_button = WebDriverWait(self.driver, 30).until(ec.visibility_of_element_located((By.XPATH, "//*[@id='__next']/div/main/section/div/div/div[1]/div/a[2] ")))
    #  user_experiences_button.click()

     corporationName = MyExperiencesPage.get_corporationName_element(self)  
     corporationName.send_keys("To")
      
     position = MyExperiencesPage.get_position_element(self) 
     position.send_keys("Sof")
      
     sector = MyExperiencesPage.get_sector_element(self) 
     sector.send_keys("Yazı")

     start_calender = MyExperiencesPage.get_startCalendar_element(self)
     start_calender.send_keys("30.03.2020")

     finish_calender = MyExperiencesPage.get_finishCalendar_element(self)
     finish_calender.send_keys("30.03.2023")

     save_button = MyExperiencesPage.get_saveButton_element(self) 
     #save_button.click()
     self.driver.execute_script("arguments[0].click();", save_button)

     corporationName_warningField = MyExperiencesPage.get_corporationNameWarningField_element(self)
     assert corporationName_warningField.text == "En az 5 karakter girmelisiniz"
     position_warningField = MyExperiencesPage.get_positionWarningField_element(self)
     assert position_warningField.text == "En az 5 karakter girmelisiniz"
     sector_warningField = MyExperiencesPage.get_sectorWarningField_element(self)
     assert sector_warningField.text == "En az 5 karakter girmelisiniz"
     sleep(5)
