# Test Senaryosunun Adı: Profil Bilgileri altında deneyimlerim bölümü bilgi ekleme/güncelleme kontrolleri
# TEST CASE 1:  Başarılı deneyim ekleme kontrolü

# Profil Bilgileri -> Deneyimlerim Sayfası 
# https://tobeto.com/profilim/profilimi-duzenle/deneyimlerim

# Generated by Selenium IDE
import pytest
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

import tests.loginTests.test_validLogin as login
import constants.my_experiences_page_constants as gc
from pages.my_experiences_page import MyExperiencesPage
from time import sleep

class TestAddExperience():
  def setup_method(self):
    # as a precondition user should be logged in
    valid_login = login.TestvalidLogin() 
    valid_login.setup_method()
    valid_login.test_validLogin()
    self.driver = valid_login.getDriver()
    
    self.driver.delete_all_cookies
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
    
  @pytest.mark.skip()
  def test_addExperience(self):
    
      # go to page "Deneyimlerim"
      #WebDriverWait(self.driver, 30).until(ec.invisibility_of_element_located(((By.CSS_SELECTOR, ".toast-body"))))

      #user_profile_button = WebDriverWait(self.driver, 30).until(ec.presence_of_element_located((By.XPATH, gc.USER_PROFILE_BUTTON_XPATH)))
      
      #user_profile_button.click()
      #user_profile_info_button = WebDriverWait(self.driver, 30).until(ec.visibility_of_element_located((By.XPATH, "//*[@id='__next']/div/nav/div[1]/div/div/div[2]/ul/li[1]/a")))
      #user_profile_info_button.click()

      #is_on_profile_page = WebDriverWait(self.driver, 30).until(ec.visibility_of_element_located((By.XPATH, "//*[@id='__next']/div/main/section/div/div/div[1]/div/a[1]/span[2]")))
      #assert is_on_profile_page.text == "Kişisel Bilgilerim"
      #user_experiences_button = WebDriverWait(self.driver, 30).until(ec.visibility_of_element_located((By.XPATH, "//*[@id='__next']/div/main/section/div/div/div[1]/div/a[2] ")))
      #user_experiences_button.click()
      
      self.driver.get("https://tobeto.com/profilim/profilimi-duzenle/deneyimlerim")

      #for i in range(0,100):
      corporationName = MyExperiencesPage.get_corporationName_element   # WebDriverWait(self.driver, 30).until(ec.visibility_of_element_located((By.XPATH, "//div[@id='__next']/div/main/section/div/div/div[2]/form/div/div/input")))
      corporationName.send_keys("testKubra")
      
      position = WebDriverWait(self.driver, 30).until(ec.visibility_of_element_located((By.XPATH, "//div[@id=\'__next\']/div/main/section/div/div/div[2]/form/div/div[2]/input")))
      position.send_keys("testKubra")
      
      sector = WebDriverWait(self.driver, 30).until(ec.visibility_of_element_located((By.XPATH, "//div[@id=\'__next\']/div/main/section/div/div/div[2]/form/div/div[3]/input")))
      sector.send_keys("testKubra")
      
      select_country_dropdown= WebDriverWait(self.driver, 30).until(ec.visibility_of_element_located((By.XPATH, "//div[@id=\'__next\']/div/main/section/div/div/div[2]/form/div/div[4]/select")))
      select_option = select_country_dropdown.find_element(By.XPATH, "//option[. = 'İstanbul']")
      select_option.click()
        
      start_calender = WebDriverWait(self.driver, 30).until(ec.visibility_of_element_located((By.XPATH, "//div[@id=\'__next\']/div/main/section/div/div/div[2]/form/div/div[5]/div/div/input")))
      start_calender.click()
      
      start_date = WebDriverWait(self.driver, 30).until(ec.visibility_of_element_located((By.CSS_SELECTOR, ".react-datepicker__day--020")))
      start_date.click()
      
      finish_calender = WebDriverWait(self.driver, 30).until(ec.visibility_of_element_located((By.XPATH, "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[6]/div/div/input")))
      finish_calender.click()
        
      finish_date = WebDriverWait(self.driver, 30).until(ec.visibility_of_element_located((By.CSS_SELECTOR, ".react-datepicker__day--026")))
      finish_date.click()

      sleep(5)
      save_button = WebDriverWait(self.driver, 30).until(ec.visibility_of_element_located((By.CSS_SELECTOR, ".btn-primary")))
      save_button.click()

      toast_message_text = WebDriverWait(self.driver, 5).until(ec.presence_of_element_located((By.CSS_SELECTOR, ".toast-body")))
      assert toast_message_text.text == "• Deneyim eklendi."
        
  
