# TEST CASE: Yabancı dil ekle

# Profil Bilgileri -> Yabancı Dillerim Sayfası Locators
# https://tobeto.com/profilim/profilimi-duzenle/yabanci-dil

# Generated by Selenium IDE
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait 
from selenium.webdriver.support import expected_conditions as ec 
import pytest
import tests.loginTests.test_validLogin as login
from time import sleep

class Test_add_language:
    
    def setup_method(self): 
        valid_login = login.TestvalidLogin() 
        valid_login.setup_method()
        valid_login.test_validLogin()
        self.driver = valid_login.getDriver()
    
        self.driver.delete_all_cookies
        self.vars = {}
        
        # WebDriverWait(self.driver, 30).until(ec.invisibility_of_element_located(((By.CSS_SELECTOR, ".toast-body"))))
        # sleep(5)
        # name_button = self.driver.find_element(By.XPATH,"//*[@id='__next']/div/nav/div[1]/div/div/div[2]")
        # name_button.click()

        # profil = WebDriverWait(self.driver, 30).until(ec.visibility_of_element_located((By.XPATH,"//*[@id='__next']/div/nav/div[1]/div/div/div[2]/ul/li[1]/a")))
        # profil.click()

        # foreign_languages = self.driver.find_element(By.XPATH, "//*[@id='__next']/div/main/section/div/div/div[1]/div/a[7]/span[2]")
        # foreign_languages.click()

    def teardown_method(self): 
        self.driver.quit()

    #@pytest.mark.skip()
    def test_add_name(self):
      
      self.driver.get("https://tobeto.com/profilim/profilimi-duzenle/yabanci-dil")
      
      #self.driver.find_element(By.XPATH, "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[1]/select").click()
      #dropdown = self.driver.find_element(By.XPATH, "xpath=//select[@name='languageName']")
      language_dropdown = self.driver.find_element(By.NAME, "languageName")
      language_dropdown.click()
      sleep(5)
      language_dropdown.find_element(By.XPATH, "//option[. = 'Almanca']").click()
      
      #self.driver.find_element(By.XPATH, "xpath=//select[@name='proficiency']").click()
      proficiency_dropdown = self.driver.find_element(By.NAME, "proficiency")
      proficiency_dropdown.click()
      sleep(5)
      proficiency_dropdown.find_element(By.XPATH, "//option[. = 'İleri Seviye (C1 , C2)']").click()

      save_button = WebDriverWait(self.driver, 5).until(ec.presence_of_element_located((By.XPATH, "//form/button")))
      save_button.click()
      #self.driver.find_element(By.XPATH, "//form/button").click()
      #sleep(5)
      #WebDriverWait(self.driver, 5).until(ec.presence_of_element_located((By.XPATH, "//body/div/div/div[2]/div/div[2]")))
      
      toast_message =  WebDriverWait(self.driver, 500).until(ec.presence_of_element_located((By.CSS_SELECTOR, ".toast-body")))
      assert toast_message.text == "• Yabancı dil bilgisi eklendi."
      sleep(5)
      self.driver.close()