# Login Page 
# https://tobeto.com/giris

# Generated by Selenium IDE
import pytest
from time import sleep
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from pages.login_page import LoginPage
import constants.globalConstants as gc 

from constants import globalConstants as gc
import openpyxl

class TestblankLogin():
  def setup_method(self):
    #self.driver = webdriver.Chrome()
    #self.driver.get("https://tobeto.com/giris")
    #self.driver.maximize_window()
    LoginPage.gotoPage(self)
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()

  #@pytest.mark.skip()
  def test_blankLogin(self):
    
    giris_button = LoginPage.get_girisButton_element(self)
    giris_button.click()

    warning_field_mail = LoginPage.get_warningFieldMail_element(self)
    assert warning_field_mail.text == "Doldurulması zorunlu alan*"

    warning_field_pass = LoginPage.get_warningFieldPass_element(self)
    assert warning_field_pass.text == "Doldurulması zorunlu alan*"
    sleep(5)
