# Generated by Selenium IDE
# Profil Bilgileri -> Yetkinliklerim Düzenleme sayfası Locators
#Yetkinlik Ekleme Testi
# https://tobeto.com/profilim/profilimi-duzenle/yetkinliklerim
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

import tests.loginTests.test_validLogin as login
from pages.competence import competence_add

from time import sleep


class TestCompetenceAdd():
 
  def setup_method(self):
    # as a precondition user should be logged in
    valid_login = login.TestvalidLogin() 
    valid_login.setup_method()
    valid_login.test_validLogin()
    self.driver = valid_login.getDriver()
    
    self.driver.delete_all_cookies
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_competenceadd(self):
    self.driver.get("https://tobeto.com/profilim/profilimi-duzenle/yetkinliklerim")
    self.driver.set_window_size(1552, 832)
    
    competence = competence_add.get_competence_add(self)
    competence.find_element(By.ID, "react-select-2-input").send_keys("alala")
    competence.find_element(By.ID, "react-select-2-input").send_keys(Keys.ENTER)
  
    toast_message = competence_add.get_toast_message(self)
    assert toast_message.text == "• Yetenek eklendi."
  
  
  sleep(5)